# docker/Dockerfile.api
FROM python:3.12-slim

WORKDIR /app

# dépendances système minimales (psycopg2, etc.)
RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

# Copie des fichiers de config Python
COPY pyproject.toml ./

# Installation des deps
RUN pip install --upgrade pip && \
    pip install .

# Copie du code
COPY src ./src
COPY scripts ./scripts

ENV PYTHONPATH=/app/src